import PDFDocument from "pdfkit";
import fs from "fs";
import path from "path";

function ensureDir(dir: string) {
  fs.mkdirSync(dir, { recursive: true });
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(amount);
}

const DOCS_DIR = path.join("uploads", "documents");

// ─── Purchase Agreement ───────────────────────────────────────────────────────
export function generatePurchaseAgreement(data: {
  buyerName: string;
  sellerName: string;
  propertyAddress: string;
  purchasePrice: number;
  closingDate: string;
  contingencies: string[];
}): string {
  ensureDir(DOCS_DIR);
  const filename = `purchase-agreement-${Date.now()}.pdf`;
  const filepath = path.join(DOCS_DIR, filename);

  const doc = new PDFDocument({ margin: 72, size: "LETTER" });
  const stream = fs.createWriteStream(filepath);
  doc.pipe(stream);

  // Header
  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("RESIDENTIAL PURCHASE AGREEMENT", { align: "center" });
  doc.moveDown(0.5);
  doc
    .fontSize(10)
    .font("Helvetica")
    .text("HomeDirect Platform — For-Sale-By-Owner Transaction", { align: "center" });
  doc.moveDown(1.5);

  // Divider
  doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke();
  doc.moveDown(1);

  // Parties
  doc.fontSize(13).font("Helvetica-Bold").text("PARTIES");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Buyer:   ${data.buyerName}`);
  doc.text(`Seller:  ${data.sellerName}`);
  doc.moveDown(1);

  // Property
  doc.fontSize(13).font("Helvetica-Bold").text("PROPERTY");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Address: ${data.propertyAddress}`);
  doc.moveDown(1);

  // Purchase Price
  doc.fontSize(13).font("Helvetica-Bold").text("PURCHASE PRICE");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Purchase Price:     ${formatCurrency(data.purchasePrice)}`);
  doc.text(`Platform Fee (1%):  ${formatCurrency(data.purchasePrice * 0.01)}`);
  doc.text(`Estimated Net:      ${formatCurrency(data.purchasePrice * 0.99)}`);
  doc.moveDown(1);

  // Closing Date
  doc.fontSize(13).font("Helvetica-Bold").text("CLOSING DATE");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Target Closing Date: ${data.closingDate}`);
  doc.moveDown(1);

  // Contingencies
  if (data.contingencies.length > 0) {
    doc.fontSize(13).font("Helvetica-Bold").text("CONTINGENCIES");
    doc.moveDown(0.5);
    doc.fontSize(11).font("Helvetica");
    data.contingencies.forEach((c) => {
      doc.text(`  • ${c} Contingency`);
    });
    doc.moveDown(1);
  }

  // Terms
  doc.fontSize(13).font("Helvetica-Bold").text("GENERAL TERMS");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  const terms = [
    "1. This Agreement is contingent upon Buyer obtaining financing at an interest rate not to exceed market rates at time of closing.",
    "2. Seller warrants that the property will be delivered free and clear of all liens, except those specifically assumed by Buyer.",
    "3. Closing costs shall be allocated as customary in the county where the property is located.",
    "4. Possession shall transfer to Buyer at closing unless otherwise agreed in writing.",
    "5. This Agreement constitutes the entire agreement between the parties and supersedes all prior negotiations.",
    "6. All representations, warranties, covenants, and obligations are binding upon the parties and their successors.",
    "7. Time is of the essence with respect to all dates and deadlines in this Agreement.",
  ];
  terms.forEach((t) => {
    doc.text(t, { indent: 0 });
    doc.moveDown(0.5);
  });
  doc.moveDown(0.5);

  // Signatures
  doc.addPage();
  doc.fontSize(13).font("Helvetica-Bold").text("SIGNATURES");
  doc.moveDown(1);

  const signY = doc.y;

  // Buyer signature block
  doc.fontSize(11).font("Helvetica");
  doc.text("BUYER SIGNATURE", 72, signY);
  doc.moveDown(2);
  doc.moveTo(72, doc.y).lineTo(300, doc.y).stroke();
  doc.moveDown(0.3);
  doc.fontSize(9).text(`${data.buyerName} (Buyer)`, 72);
  doc.text("Date: ________________", 72);

  // Seller signature block
  doc.fontSize(11).font("Helvetica").text("SELLER SIGNATURE", 320, signY);
  doc.moveTo(320, signY + 48).lineTo(540, signY + 48).stroke();
  doc.fontSize(9).text(`${data.sellerName} (Seller)`, 320, signY + 52);
  doc.text("Date: ________________", 320, signY + 65);

  doc.moveDown(4);
  doc
    .fontSize(8)
    .fillColor("#888888")
    .text(
      `Generated by HomeDirect on ${new Date().toLocaleDateString()}. This document is provided for informational purposes. Consult an attorney before signing.`,
      { align: "center" }
    );

  doc.end();

  // Wait for the stream to finish (synchronous-ish via sync write)
  return `/uploads/documents/${filename}`;
}

// ─── Seller Disclosure ────────────────────────────────────────────────────────
export function generateSellerDisclosure(data: {
  sellerName: string;
  propertyAddress: string;
  yearBuilt?: number;
}): string {
  ensureDir(DOCS_DIR);
  const filename = `seller-disclosure-${Date.now()}.pdf`;
  const filepath = path.join(DOCS_DIR, filename);

  const doc = new PDFDocument({ margin: 72, size: "LETTER" });
  doc.pipe(fs.createWriteStream(filepath));

  doc
    .fontSize(18)
    .font("Helvetica-Bold")
    .text("SELLER'S PROPERTY DISCLOSURE STATEMENT", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica").text("HomeDirect Platform", { align: "center" });
  doc.moveDown(1);
  doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke();
  doc.moveDown(1);

  doc.fontSize(11).font("Helvetica");
  doc.text(`Seller: ${data.sellerName}`);
  doc.text(`Property: ${data.propertyAddress}`);
  if (data.yearBuilt) doc.text(`Year Built: ${data.yearBuilt}`);
  doc.moveDown(1);

  doc
    .fontSize(10)
    .text(
      "INSTRUCTIONS TO SELLER: Complete this form carefully. Disclose all known material defects. " +
        "Check YES, NO, or UNKNOWN for each item. Add comments where applicable."
    );
  doc.moveDown(1);

  const sections: { title: string; items: string[] }[] = [
    {
      title: "STRUCTURAL",
      items: [
        "Foundation cracks or settling",
        "Roof leaks or damage (within 5 years)",
        "Water intrusion in basement/crawl space",
        "Previous structural repairs",
      ],
    },
    {
      title: "MECHANICAL SYSTEMS",
      items: [
        "HVAC system defects",
        "Plumbing leaks or issues",
        "Electrical panel defects",
        "Water heater age/condition issues",
      ],
    },
    {
      title: "ENVIRONMENTAL",
      items: [
        "Known asbestos presence",
        "Lead paint (pre-1978 homes)",
        "Mold or mildew",
        "Underground storage tanks",
      ],
    },
    {
      title: "LEGAL/PROPERTY",
      items: [
        "Pending lawsuits affecting property",
        "HOA violations or pending assessments",
        "Easements not shown in public records",
        "Zoning violations",
      ],
    },
  ];

  sections.forEach((section) => {
    doc.fontSize(12).font("Helvetica-Bold").text(section.title);
    doc.moveDown(0.4);
    section.items.forEach((item) => {
      doc.fontSize(10).font("Helvetica");
      doc.text(`□ YES  □ NO  □ UNKNOWN    ${item}`);
      doc.text("    Comments: ________________________________________________________________", {
        indent: 20,
      });
      doc.moveDown(0.4);
    });
    doc.moveDown(0.5);
  });

  // Seller certification
  doc.addPage();
  doc.fontSize(12).font("Helvetica-Bold").text("SELLER CERTIFICATION");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(
    "The Seller certifies that the information contained in this disclosure statement is accurate " +
      "and complete to the best of the Seller's knowledge as of the date signed below. Seller agrees " +
      "to disclose any changes to this information that become known prior to closing."
  );
  doc.moveDown(2);
  doc.moveTo(72, doc.y).lineTo(320, doc.y).stroke();
  doc.moveDown(0.3);
  doc.text(`${data.sellerName} (Seller)`);
  doc.text("Date: ________________");

  doc.end();
  return `/uploads/documents/${filename}`;
}

// ─── Closing Disclosure ───────────────────────────────────────────────────────
export function generateClosingDisclosure(data: {
  buyerName: string;
  sellerName: string;
  propertyAddress: string;
  purchasePrice: number;
  platformFee: number;
  closingDate: string;
}): string {
  ensureDir(DOCS_DIR);
  const filename = `closing-disclosure-${Date.now()}.pdf`;
  const filepath = path.join(DOCS_DIR, filename);

  const doc = new PDFDocument({ margin: 72, size: "LETTER" });
  doc.pipe(fs.createWriteStream(filepath));

  doc
    .fontSize(20)
    .font("Helvetica-Bold")
    .text("CLOSING DISCLOSURE", { align: "center" });
  doc.moveDown(0.3);
  doc.fontSize(10).font("Helvetica").text("HomeDirect Platform — Transaction Summary", { align: "center" });
  doc.moveDown(1);
  doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke();
  doc.moveDown(1);

  // Parties
  doc.fontSize(11).font("Helvetica");
  doc.text(`Buyer:    ${data.buyerName}`);
  doc.text(`Seller:   ${data.sellerName}`);
  doc.text(`Property: ${data.propertyAddress}`);
  doc.text(`Closing:  ${data.closingDate}`);
  doc.moveDown(1);

  // Financial summary table
  doc.fontSize(13).font("Helvetica-Bold").text("FINANCIAL SUMMARY");
  doc.moveDown(0.5);
  doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).stroke();
  doc.moveDown(0.5);

  const line = (label: string, amount: number, bold = false) => {
    doc.fontSize(11).font(bold ? "Helvetica-Bold" : "Helvetica");
    const formatted = formatCurrency(Math.abs(amount));
    const prefix = amount < 0 ? "-" : " ";
    doc.text(label, 72, doc.y, { continued: true });
    doc.text(`${prefix}${formatted}`, { align: "right" });
  };

  line("Purchase Price", data.purchasePrice);
  line("HomeDirect Platform Fee (1%)", -data.platformFee);
  doc.moveDown(0.3);
  doc.moveTo(72, doc.y).lineTo(doc.page.width - 72, doc.y).dash(3, { space: 3 }).stroke().undash();
  doc.moveDown(0.3);
  line("Estimated Seller Proceeds", data.purchasePrice - data.platformFee, true);
  doc.moveDown(1.5);

  // Estimated closing cost breakdown
  const estimatedEscrow = Math.round(data.purchasePrice * 0.001);
  const estimatedTitle = 1200;
  const estimatedRecording = 150;
  const totalBuyerClosing = estimatedEscrow + estimatedTitle + estimatedRecording;

  doc.fontSize(13).font("Helvetica-Bold").text("ESTIMATED CLOSING COSTS (BUYER)");
  doc.moveDown(0.5);
  doc.fontSize(11).font("Helvetica");
  doc.text(`Escrow Fee:                ${formatCurrency(estimatedEscrow)}`);
  doc.text(`Title Insurance:           ${formatCurrency(estimatedTitle)}`);
  doc.text(`Recording Fees:            ${formatCurrency(estimatedRecording)}`);
  doc.moveDown(0.3);
  doc.moveTo(72, doc.y).lineTo(300, doc.y).stroke();
  doc.moveDown(0.3);
  doc.font("Helvetica-Bold").text(`Total Estimated Buyer Closing: ${formatCurrency(totalBuyerClosing)}`);
  doc.moveDown(1.5);

  doc
    .fontSize(9)
    .font("Helvetica")
    .fillColor("#666666")
    .text(
      "NOTE: This is an estimate only. Actual closing costs may vary. All figures subject to final lender approval and title review. " +
        "Please review with your attorney or closing agent.",
      { align: "left" }
    );
  doc.fillColor("#000000");
  doc.moveDown(2);

  // Signatures
  doc.fontSize(13).font("Helvetica-Bold").text("ACKNOWLEDGMENT");
  doc.moveDown(0.5);
  doc.fontSize(10).font("Helvetica");
  doc.text(
    "By signing below, the parties acknowledge receipt of this Closing Disclosure at least 3 business days before closing."
  );
  doc.moveDown(1.5);

  const sy = doc.y;
  doc.moveTo(72, sy).lineTo(260, sy).stroke();
  doc.fontSize(9).text(`${data.buyerName} (Buyer)`, 72, sy + 4);
  doc.text("Date: ________________", 72, sy + 17);

  doc.moveTo(300, sy).lineTo(490, sy).stroke();
  doc.text(`${data.sellerName} (Seller)`, 300, sy + 4);
  doc.text("Date: ________________", 300, sy + 17);

  doc.end();
  return `/uploads/documents/${filename}`;
}
